#!/usr/bin/env python3
"""build_corpus.py — extract tech corpus from ALGAE → data/corpus.js

Pulls Wikidata entities that are subclasses (transitive P279) of Q11016
(technology), filtered by Wikipedia language coverage. Emits a JS file
that defines window.CORPUS so the static SPA can load it via <script>.
"""
import argparse
import json
import sys
from pathlib import Path

import psycopg

# Subclass-of-technology entries that are technically valid but aren't
# useful as game material.
BLOCKLIST = {
    "Q11016",  # Technology (the root itself)
    "Q33057",  # ISBN
    "Q421",    # Unidentified flying object
}

QUERY = """
SELECT e.qid, l.label, e.wp_count
FROM wd_entities e
JOIN subclass_closure sc ON e.qid = sc.sub_qid
JOIN wd_labels l ON e.qid = l.qid AND l.lang = 'en'
WHERE sc.super_qid = 'Q11016'
  AND e.wp_count >= %s
ORDER BY e.wp_count DESC, e.qid, length(l.label)
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--min-wp", type=int, default=20,
                    help="minimum Wikipedia language coverage (default 20)")
    ap.add_argument("--db", default="algae", help="postgres database name")
    ap.add_argument("--out", default="data/corpus.js",
                    help="output path (relative to repo root)")
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / args.out

    with psycopg.connect(f"dbname={args.db}") as conn, conn.cursor() as cur:
        cur.execute(QUERY, (args.min_wp,))
        rows = cur.fetchall()

    # An entity can have multiple english labels; keep the first (shortest)
    # we see — query is ordered so the canonical short label wins.
    seen = set()
    corpus = []
    for qid, label, wp_count in rows:
        if qid in BLOCKLIST or qid in seen or not label:
            continue
        seen.add(qid)
        corpus.append({
            "qid": qid,
            "name": label,
            "wp_count": wp_count,
            "emoji": None,
            "blurb": None,
            "tags": [],
        })

    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(corpus, ensure_ascii=False, indent=2)
    header = (
        "// Auto-generated by pipeline/build_corpus.py — do not edit by hand.\n"
        f"// {len(corpus)} technologies, ALGAE subclass* of Q11016, "
        f"wp_count >= {args.min_wp}.\n"
    )
    out_path.write_text(f"{header}window.CORPUS = {body};\n", encoding="utf-8")
    print(f"wrote {len(corpus)} techs → {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
