#!/usr/bin/env python3
"""cleanup_corpus.py — apply policy.CORPUS_BLOCKLIST_QIDS and
policy.MANUAL_CORPUS_ADDS to data/corpus.js without rebuilding from ALGAE.

Idempotent: re-running drops blocked entries (if any are still present) and
inserts manual adds (if missing). Re-runs the corpus header counts.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from policy import CORPUS_BLOCKLIST_QIDS, MANUAL_CORPUS_ADDS


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus", default="data/corpus.js")
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    corpus_path = repo_root / args.corpus

    src = corpus_path.read_text(encoding="utf-8")
    body = src.split("window.CORPUS = ", 1)[1].rstrip().rstrip(";").strip()
    corpus = json.loads(body)
    by_qid = {e["qid"]: e for e in corpus}

    # Apply blocklist.
    before = len(corpus)
    blocked_present = [e for e in corpus if e["qid"] in CORPUS_BLOCKLIST_QIDS]
    corpus = [e for e in corpus if e["qid"] not in CORPUS_BLOCKLIST_QIDS]
    by_qid = {e["qid"]: e for e in corpus}

    # Apply manual adds (insert if missing; do not overwrite if present).
    added = []
    for entry in MANUAL_CORPUS_ADDS:
        if entry["qid"] in by_qid:
            continue
        # Ensure expected schema keys.
        rec = {
            "qid": entry["qid"],
            "name": entry["name"],
            "wp_count": entry.get("wp_count", 0),
            "emoji": entry.get("emoji"),
            "blurb": entry.get("blurb"),
            "tags": list(entry.get("tags", [])),
        }
        corpus.append(rec)
        by_qid[rec["qid"]] = rec
        added.append(rec)

    # Re-sort: tagged entries first by wp_count desc, untagged by wp_count desc.
    corpus.sort(key=lambda e: (-bool(e["tags"]), -(e["wp_count"] or 0), e["qid"]))

    n_emerging = sum(1 for e in corpus if "emerging" in e["tags"])
    n_hypothetical = sum(1 for e in corpus if "hypothetical" in e["tags"])
    n_with_emoji = sum(1 for e in corpus if e.get("emoji"))
    n_with_blurb = sum(1 for e in corpus if e.get("blurb"))

    header = (
        "// Auto-generated by pipeline/build_corpus.py + parse_wiki_lists.py "
        "+ merge_descriptions.py + cleanup_corpus.py.\n"
        f"// {len(corpus)} technologies total — "
        f"{n_emerging} tagged 'emerging', {n_hypothetical} tagged 'hypothetical'. "
        f"{n_with_emoji} have emojis, {n_with_blurb} have blurbs.\n"
    )
    out = json.dumps(corpus, ensure_ascii=False, indent=2)
    corpus_path.write_text(f"{header}window.CORPUS = {out};\n", encoding="utf-8")

    print(f"corpus: {before} → {len(corpus)} entries", file=sys.stderr)
    print(f"  dropped {len(blocked_present)} blocked entries:", file=sys.stderr)
    for e in blocked_present:
        print(f"    {e['qid']:<12}  {e['name']}", file=sys.stderr)
    print(f"  inserted {len(added)} manual entries:", file=sys.stderr)
    for e in added:
        print(f"    {e['qid']:<12}  {e['name']}", file=sys.stderr)


if __name__ == "__main__":
    main()
