#!/usr/bin/env python3
"""merge_next_level.py — append next-level combo batches into the existing
data/combinations.js (does not rebuild from scratch).

Validates parent IDs against the union of core QIDs and existing syn IDs in
combinations.js, and validates pairs against pipeline/next_level_pairs.json.
Idempotent: re-running skips pairs already present in combinations.js.
"""
import argparse
import datetime as dt
import hashlib
import json
import re
import sys
from pathlib import Path


def norm_name(name: str) -> str:
    s = name.lower()
    s = re.sub(r"[^\w\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def synth_id(name: str) -> str:
    h = hashlib.sha256(norm_name(name).encode("utf-8")).hexdigest()[:10]
    return f"syn_{h}"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--pattern", default="combinations_next_batch_*.json")
    ap.add_argument("--pairs", default="pipeline/next_level_pairs.json")
    ap.add_argument("--out", default="data/combinations.js")
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    data_dir = repo_root / args.data_dir
    out_path = repo_root / args.out

    # Load existing combinations.js as a list.
    src = out_path.read_text(encoding="utf-8")
    body = src.split("window.COMBINATIONS = ", 1)[1].rstrip().rstrip(";").strip()
    combos: list[dict] = json.loads(body)
    have_pair = {tuple(sorted(c["parents"])) for c in combos}
    have_id = {c["id"] for c in combos}

    # Build the valid-ID universe: every QID in the corpus + synth IDs
    # already in combinations.js. Corpus is the source of truth for "is this
    # a real Wikidata entity in scope" — it's already filtered by policy.
    corpus_src = (repo_root / "data" / "corpus.js").read_text()
    corpus_body = corpus_src.split("window.CORPUS = ", 1)[1].rstrip().rstrip(";").strip()
    corpus_qids = {e["qid"] for e in json.loads(corpus_body)}
    valid_ids = corpus_qids | have_id

    # Load expected next-level pair list.
    expected_pairs = {tuple(sorted(p)) for p in
                      json.loads((repo_root / args.pairs).read_text())}

    batch_paths = sorted(data_dir.glob(args.pattern))
    if not batch_paths:
        print(f"no batch files matching {args.pattern!r}", file=sys.stderr)
        sys.exit(1)

    added = 0
    skipped: list[tuple[str, str, str]] = []
    for path in batch_paths:
        try:
            entries = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            print(f"ERROR: {path.name}: {e}", file=sys.stderr)
            sys.exit(2)
        for e in entries:
            a, b = e.get("qid_a"), e.get("qid_b")
            if not a or not b:
                skipped.append((str(a), str(b), "missing qid"))
                continue
            if a not in valid_ids or b not in valid_ids:
                skipped.append((a, b, "id not in valid universe"))
                continue
            pair = tuple(sorted([a, b]))
            if pair not in expected_pairs:
                skipped.append((a, b, "not in expected pair list"))
                continue
            if pair in have_pair:
                skipped.append((a, b, "already in combinations.js"))
                continue
            name = (e.get("name") or "").strip()
            if not name:
                skipped.append((a, b, "missing name"))
                continue
            combos.append({
                "parents": list(pair),
                "id": synth_id(name),
                "name": name,
                "emoji": (e.get("emoji") or "✦").strip()[:4] or "✦",
                "blurb": (e.get("blurb") or "").strip(),
            })
            have_pair.add(pair)
            added += 1

    missing_pairs = expected_pairs - have_pair
    if missing_pairs:
        print(f"WARNING: {len(missing_pairs)} expected pairs missing", file=sys.stderr)

    # Re-sort by parents for stable diff.
    combos.sort(key=lambda c: (c["parents"][0], c["parents"][1]))

    n_unique_synths = len({c["id"] for c in combos})
    n_converged = len(combos) - n_unique_synths
    header = (
        "// Auto-generated by pipeline/merge_combos.py + merge_next_level.py — do not edit by hand.\n"
        f"// {len(combos)} pair → synthesis records, "
        f"{n_unique_synths} unique synthesized technologies "
        f"({n_converged} convergent collisions).\n"
    )
    out_text = json.dumps(combos, ensure_ascii=False, indent=2)
    out_path.write_text(f"{header}window.COMBINATIONS = {out_text};\n", encoding="utf-8")

    print(
        f"+{added} next-level combos appended, {len(skipped)} skipped. "
        f"combinations.js now: {len(combos)} records, "
        f"{n_unique_synths} unique synths ({n_converged} convergent).",
        file=sys.stderr,
    )

    # Update manifest with the new run.
    manifest_path = repo_root / "data" / "manifest.json"
    if manifest_path.exists():
        m = json.loads(manifest_path.read_text())
    else:
        m = {}
    runs = m.setdefault("runs", [])
    runs.append({
        "ran_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "kind": "next_level_merge",
        "pattern": args.pattern,
        "added": added,
        "skipped": len(skipped),
    })
    m["n_pairs_in_combinations"] = len(combos)
    m["n_unique_synths"] = n_unique_synths
    m["n_convergent_collisions"] = n_converged
    manifest_path.write_text(json.dumps(m, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
