#!/usr/bin/env python3
"""merge_combos.py — combine all data/combinations_batch_*.json into a single
data/combinations.js, plus write data/manifest.json with run metadata.

Synthesized-tech IDs are derived from a normalized form of the result name
so different pairs that converge on the same name share an ID — this gives
the DAG real fan-in instead of being a pure tree.
"""
import argparse
import datetime as dt
import glob
import hashlib
import json
import re
import sys
from pathlib import Path


def norm_name(name: str) -> str:
    """Lowercased, punctuation-stripped, whitespace-collapsed name for hashing."""
    s = name.lower()
    s = re.sub(r"[^\w\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def synth_id(name: str) -> str:
    h = hashlib.sha256(norm_name(name).encode("utf-8")).hexdigest()[:10]
    return f"syn_{h}"


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--out", default="data/combinations.js")
    ap.add_argument("--manifest", default="data/manifest.json")
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    data_dir = repo_root / args.data_dir
    out_path = repo_root / args.out
    manifest_path = repo_root / args.manifest

    batch_paths = sorted(data_dir.glob("combinations_batch_*.json"))
    if not batch_paths:
        print("no batch files found", file=sys.stderr)
        sys.exit(1)

    # Validate against the source-of-truth pair list.
    pairs = json.loads((repo_root / "pipeline" / "pairs.json").read_text())
    expected_pairs = {tuple(p) for p in pairs}

    # Validate core lookup is available too.
    core = json.loads((repo_root / "pipeline" / "core_techs.json").read_text())
    valid_qids = {e["qid"] for e in core}

    seen_pairs: set[tuple[str, str]] = set()
    combos: list[dict] = []
    skipped: list[tuple[str, str, str]] = []  # (qid_a, qid_b, reason)

    for path in batch_paths:
        try:
            entries = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            print(f"ERROR: {path.name}: {e}", file=sys.stderr)
            sys.exit(2)
        for e in entries:
            a, b = e.get("qid_a"), e.get("qid_b")
            if not a or not b:
                skipped.append((str(a), str(b), "missing qid"))
                continue
            if a not in valid_qids or b not in valid_qids:
                skipped.append((a, b, "qid not in core"))
                continue
            pair = tuple(sorted([a, b]))
            if pair not in expected_pairs:
                skipped.append((a, b, "not in pairs.json"))
                continue
            if pair in seen_pairs:
                skipped.append((a, b, "duplicate pair across batches"))
                continue
            name = (e.get("name") or "").strip()
            if not name:
                skipped.append((a, b, "missing name"))
                continue
            combos.append({
                "parents": list(pair),
                "id": synth_id(name),
                "name": name,
                "emoji": (e.get("emoji") or "✦").strip()[:4] or "✦",
                "blurb": (e.get("blurb") or "").strip(),
            })
            seen_pairs.add(pair)

    missing_pairs = expected_pairs - seen_pairs
    if missing_pairs:
        print(f"WARNING: {len(missing_pairs)} pairs missing from batches", file=sys.stderr)
        for a, b in sorted(missing_pairs)[:10]:
            print(f"  - {a} + {b}", file=sys.stderr)

    # Stable sort: by parents pair so the file diffs cleanly across re-runs.
    combos.sort(key=lambda c: (c["parents"][0], c["parents"][1]))

    body = json.dumps(combos, ensure_ascii=False, indent=2)
    n_unique_synths = len({c["id"] for c in combos})
    n_converged = len(combos) - n_unique_synths
    header = (
        "// Auto-generated by pipeline/merge_combos.py — do not edit by hand.\n"
        f"// {len(combos)} pair → synthesis records, "
        f"{n_unique_synths} unique synthesized technologies "
        f"({n_converged} convergent collisions).\n"
    )
    out_path.write_text(f"{header}window.COMBINATIONS = {body};\n", encoding="utf-8")
    print(
        f"wrote {len(combos)} combinations ({n_unique_synths} unique, "
        f"{n_converged} convergent), {len(skipped)} skipped → {out_path}",
        file=sys.stderr,
    )

    # Manifest.
    manifest = {
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "model": "claude-sonnet-4-6 (via subagents)",
        "batch_files": [p.name for p in batch_paths],
        "n_pairs_expected": len(expected_pairs),
        "n_pairs_covered": len(seen_pairs),
        "n_pairs_missing": len(missing_pairs),
        "n_skipped_entries": len(skipped),
        "n_unique_synths": n_unique_synths,
        "n_convergent_collisions": n_converged,
        "checksums": {
            "pipeline/combine_prompt.txt": file_sha256(repo_root / "pipeline" / "combine_prompt.txt"),
            "pipeline/core_techs.json":    file_sha256(repo_root / "pipeline" / "core_techs.json"),
            "pipeline/pairs.json":         file_sha256(repo_root / "pipeline" / "pairs.json"),
            "data/corpus.js":              file_sha256(repo_root / "data" / "corpus.js"),
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"wrote manifest → {manifest_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
