#!/usr/bin/env python3
"""merge_descriptions.py — fold data/descriptions_batch_*.json back into
data/corpus.js (filling in emoji + blurb fields). Idempotent: re-running
overwrites existing values, so a follow-up batch can correct earlier output.
"""
import argparse
import json
import sys
from pathlib import Path


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--corpus", default="data/corpus.js")
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    data_dir = repo_root / args.data_dir
    corpus_path = repo_root / args.corpus

    batch_paths = sorted(data_dir.glob("descriptions_batch_*.json"))
    if not batch_paths:
        print("no description-batch files found", file=sys.stderr)
        sys.exit(1)

    # Load corpus.
    src = corpus_path.read_text(encoding="utf-8")
    body = src.split("window.CORPUS = ", 1)[1].rstrip().rstrip(";").strip()
    corpus: list[dict] = json.loads(body)
    by_qid = {e["qid"]: e for e in corpus}

    # Apply each batch.
    updated = 0
    skipped_unknown = 0
    for path in batch_paths:
        try:
            entries = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            print(f"ERROR: {path.name}: {e}", file=sys.stderr)
            sys.exit(2)
        for e in entries:
            qid = e.get("qid")
            target = by_qid.get(qid)
            if target is None:
                skipped_unknown += 1
                continue
            emoji = (e.get("emoji") or "").strip()
            blurb = (e.get("blurb") or "").strip()
            if emoji:
                target["emoji"] = emoji[:4]
            if blurb:
                target["blurb"] = blurb[:200]
            updated += 1

    n_with_emoji = sum(1 for e in corpus if e.get("emoji"))
    n_with_blurb = sum(1 for e in corpus if e.get("blurb"))
    n_emerging = sum(1 for e in corpus if "emerging" in e["tags"])
    n_hypothetical = sum(1 for e in corpus if "hypothetical" in e["tags"])

    header = (
        "// Auto-generated by pipeline/build_corpus.py + parse_wiki_lists.py "
        "+ merge_descriptions.py.\n"
        f"// {len(corpus)} technologies total — "
        f"{n_emerging} tagged 'emerging', {n_hypothetical} tagged 'hypothetical'. "
        f"{n_with_emoji} have emojis, {n_with_blurb} have blurbs.\n"
    )
    out = json.dumps(corpus, ensure_ascii=False, indent=2)
    corpus_path.write_text(f"{header}window.CORPUS = {out};\n", encoding="utf-8")

    print(
        f"applied {updated} descriptions across {len(batch_paths)} batch files "
        f"({skipped_unknown} skipped unknown qids). "
        f"corpus now: {n_with_emoji}/{len(corpus)} emoji, "
        f"{n_with_blurb}/{len(corpus)} blurb.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
