#!/usr/bin/env python3
"""prune_combinations.py — drop combinations whose parents reference any
QID in policy.CORPUS_BLOCKLIST_QIDS. Use after a cleanup_corpus run that
removes core entries.
"""
import argparse
import collections
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from policy import CORPUS_BLOCKLIST_QIDS


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="data/combinations.js")
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / args.out

    src = out_path.read_text(encoding="utf-8")
    body = src.split("window.COMBINATIONS = ", 1)[1].rstrip().rstrip(";").strip()
    combos = json.loads(body)

    before = len(combos)
    surviving: list[dict] = []
    dropped_by_parent = collections.Counter()
    for c in combos:
        bad = [p for p in c["parents"] if p in CORPUS_BLOCKLIST_QIDS]
        if bad:
            for q in bad:
                dropped_by_parent[q] += 1
            continue
        surviving.append(c)

    surviving.sort(key=lambda c: (c["parents"][0], c["parents"][1]))
    n_unique = len({c["id"] for c in surviving})
    n_converged = len(surviving) - n_unique
    header = (
        "// Auto-generated by pipeline/merge_combos.py + merge_next_level.py + prune_combinations.py.\n"
        f"// {len(surviving)} pair → synthesis records, "
        f"{n_unique} unique synthesized technologies "
        f"({n_converged} convergent collisions).\n"
    )
    out = json.dumps(surviving, ensure_ascii=False, indent=2)
    out_path.write_text(f"{header}window.COMBINATIONS = {out};\n", encoding="utf-8")

    dropped = before - len(surviving)
    print(f"combinations: {before} → {len(surviving)} ({dropped} dropped)", file=sys.stderr)
    if dropped_by_parent:
        print("  drop counts by blocked parent QID:", file=sys.stderr)
        for q, n in dropped_by_parent.most_common():
            print(f"    {q:<12}  {n} combos", file=sys.stderr)


if __name__ == "__main__":
    main()
